---
repos:
  - repo: local
    hooks:
      - id: prettier
        name: Check code formatting
        language: node
        entry: npx
        args: ["prettier", "--check"]
        exclude: |
          \.feature$
        files: \.(css|tsx?|html|js|json|yaml|md)$
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args:
          [
            "-x",
            "-a",
            "-o",
            "all",
            "-e",
            "SC2292",
            "-e",
            "SC2310",
            "-e",
            "SC2311",
            "-P",
            "./developer",
          ]
        files: \.sh$
