---
- name: Deploy IPA server for WebUI development
  hosts: ipaserver
  gather_facts: true
  become: true

  roles:
    - name: Deploy IPA server
      role: freeipa.ansible_freeipa.ipaserver
      state: present

- name: Configure modern-ui alias in httpd
  hosts: ipaserver
  gather_facts: false
  become: true
  tasks:
    - name: Modify original modern-ui to point to development version
      ansible.builtin.replace:
        path: /etc/httpd/conf.d/ipa.conf
        regexp: "/usr/share/ipa/modern-ui"
        replace: "/webui/dist"
      register: modify_ipa_conf

    - name: Ensure webui is configured in ipa.conf
      when: not modify_ipa_conf.changed
      ansible.builtin.blockinfile:
        path: /etc/httpd/conf.d/ipa.conf
        insertafter: "EOF"
        marker: "# {mark} Webui Development configuration"
        prepend_newline: true
        block: |+
          Alias /ipa/modern-ui "/webui/dist"
          <Directory "/webui/dist">
            SetHandler None
            AllowOverride None
            Satisfy Any
            Require all granted
            RewriteEngine On
            RewriteRule ^(.*)/assets/(.*)$ assets/$2 [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^ index.html [QSA,L]
          </Directory>

    - name: Temporary fix for CryptographyDeprecationWarning
      ansible.builtin.replace:
        path: /usr/lib/python3.14/site-packages/ipalib/constants.py
        regexp: '^(\s*)b"\\x00" \* 8\), modes\.CBC\(b"\\x00" \* 8\)\):'
        replace: '\1b"\\x00" * 24), modes.CBC(b"\\x00" * 8)):'

    - name: Restart web server
      ansible.builtin.systemd_service:
        name: httpd.service
        state: restarted
