---
- name: Deploy IPA server for WebUI development
  hosts: ipaserver
  gather_facts: true
  become: true

  roles:
    - name: Deploy IPA server
      role: freeipa.ansible_freeipa.ipaserver
      state: present
