FROM registry.fedoraproject.org/fedora-toolbox:41
MAINTAINER [FreeIPA Developers freeipa-devel@lists.fedorahosted.org]
ENV container=docker LANG=en_US.utf8 LANGUAGE=en_US.utf8 LC_ALL=en_US.utf8

RUN echo 'deltarpm = false' >> /etc/dnf/dnf.conf \
    && dnf update -y python3 \
    && (sed -i 's/%_install_langs \(.*\)/\0:fr/g' /etc/rpm/macros.image-language-conf ||:) \
    && dnf install -y systemd \
    && dnf install -y python3-libdnf5 \
        git \
        glibc-langpack-fr \
        glibc-langpack-en \
        iptables \
        nss-tools \
        openssh-server \
        sudo \
        wget \
        freeipa-server \
        freeipa-server-dns \
        freeipa-server-trust-ad \
        python3-libselinux \
        firewalld \
        nodejs \
    && dnf clean all \
    && sed -i 's/.*PermitRootLogin .*/#&/g' /etc/ssh/sshd_config \
    && echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config \
    && sed -i -e 's@^\(session.*required.*pam_loginuid\)@#\1@' /etc/pam.d/sshd \
    && systemctl enable sshd \
    && for i in /usr/lib/systemd/system/*-domainname.service; \
    do sed -i 's#^ExecStart=/#ExecStart=-/#' $i ; done \
    && { systemctl mask firewalld ||: ; } \
    && { systemctl mask systemd-resolved ||: ; } \
    && systemctl set-default multi-user.target

STOPSIGNAL RTMIN+3
VOLUME ["/usr/src/freeipa-webui", "/run", "/tmp"]
ENTRYPOINT [ "/usr/sbin/init" ]
