import { parseArgs } from "node:util";
import { execFileSync, execSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

type ErrorRPCResponse = {
  result: null;
  error: {
    status: string;
    code: number;
    message: string;
  };
  id: null;
  principal: string;
  version: string;
};

type ValidResponse<T> = {
  result: T;
  error: null;
  id: null;
  principal: string;
  version: string;
};

// Keep in sync with src/utils/utils.tsx → API_VERSION_BACKUP
const API_VERSION_BACKUP = "2.254";
const DEFAULT_SERVER = "https://webui.ipa.test";
const DEFAULT_CONTAINER = "webui";
const DEFAULT_OUTPUT = "src/utils/datatypes/InternationalizationKeys.ts";
const PLACEHOLDER_RE = /\$\{(\w+)\}/g;

const CLI_OPTIONS = {
  container: { type: "string", short: "c", default: DEFAULT_CONTAINER },
  server: { type: "string", short: "s", default: DEFAULT_SERVER },
  output: { type: "string", short: "o", default: DEFAULT_OUTPUT },
  help: { type: "boolean", short: "h", default: false },
} as const;

interface ParsedKey {
  flatKey: string;
  replacements: string[];
}

function printUsage(): void {
  console.log(`
Usage: npm run i18n:generate [-- options]

Fetches i18n translations from the FreeIPA server running inside the
dev container and generates typed translation keys.

Options:
  --container, -c  Container name (default: ${DEFAULT_CONTAINER})
  --server, -s     FreeIPA server URL inside the container (default: ${DEFAULT_SERVER})
  --output, -o     Output file path (default: ${DEFAULT_OUTPUT})
  --help, -h       Show this help message
`);
}

function parseCliArgs() {
  const { values } = parseArgs({
    options: CLI_OPTIONS,
    strict: true,
  });

  if (values.help) {
    printUsage();
    process.exit(0);
  }

  return {
    container: values.container,
    server: values.server,
    output: values.output,
  };
}

function fetchI18nViaContainer(container: string, serverUrl: string): object {
  const apiVersion = API_VERSION_BACKUP;
  const url = `${serverUrl.replace(/\/+$/, "")}/ipa/i18n_messages`;
  const body = JSON.stringify({
    method: "i18n_messages",
    params: [[], { version: apiVersion }],
  });

  console.log(`Fetching i18n messages via container "${container}"...`);
  console.log(`  URL: ${url} (API version: ${apiVersion})`);

  const args = [
    "exec",
    container,
    "curl",
    "-k",
    "-X",
    "POST",
    "-H",
    "Content-Type: application/json",
    "-H",
    `Referer: ${url}`,
    "-d",
    body,
    url,
  ];

  let stdout: string;
  try {
    stdout = execFileSync("podman", args, {
      encoding: "utf-8",
      timeout: 30_000,
    });
  } catch (error) {
    const err = error as Error;
    if (err.message.includes("no such container")) {
      throw new Error(
        `Container "${container}" not found. ` +
          "Is the dev environment running? (./developer/dev-env.sh)"
      );
    }
    throw new Error(`podman exec failed: ${err.message}`);
  }

  const json: ErrorRPCResponse | ValidResponse<object> = JSON.parse(stdout);

  if (json.error) {
    throw new Error(`RPC error: ${JSON.stringify(json.error)}`);
  }

  return json.result;
}

function flatten(
  obj: object | string | null | undefined,
  prefix: string = "",
  out: ParsedKey[] = []
): ParsedKey[] {
  if (obj === null || obj === undefined) return out;

  if (typeof obj === "string") {
    const replacements = [...obj.matchAll(PLACEHOLDER_RE)]
      .map((m) => m[1])
      .filter((v, i, a) => a.indexOf(v) === i);
    out.push({ flatKey: prefix, replacements });
    return out;
  }

  if (typeof obj === "object") {
    for (const [key, val] of Object.entries(obj)) {
      const nextPrefix = prefix ? `${prefix}.${key}` : key;
      flatten(val, nextPrefix, out);
    }
  }

  return out;
}

function generateTypeScript(keys: ParsedKey[]): string {
  const lines: string[] = [];

  lines.push("// Auto-generated by scripts/generate-i18n-types.ts");
  lines.push("// Do not edit manually — re-run `npm run i18n:generate`");
  lines.push("");

  lines.push("export const TRANSLATIONS = {");

  for (const key of keys) {
    lines.push(
      `  "${key.flatKey}": [${key.replacements.map((r) => `"${r}"`).join(", ")}],`
    );
  }

  lines.push("} as const;");

  return lines.join("\n");
}

function main() {
  const args = parseCliArgs();

  const data = fetchI18nViaContainer(args.container, args.server);
  const keys = flatten(data);

  console.log(`Found ${keys.length} translation keys`);

  const output = generateTypeScript(keys);
  const outPath = resolve(args.output);

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, output, "utf-8");

  execSync(`npx prettier --write ${outPath}`);
  execSync(`npx eslint --fix ${outPath}`);

  console.log(`\nGenerated ${outPath}`);
}

main();
