import { DNSName, Decimal } from "../types/primitives";
import { DnsClass } from "./dns";

export type DnsrecordAddArgs = {
  dnszoneidnsname: DNSName;
  idnsname: DNSName;
};

export type DnsrecordAddOptions = {
  dnsttl?: number;
  dnsclass?: DnsClass;
  arecord?: string;
  a_part_ip_address?: string;
  a_extra_create_reverse?: boolean;
  aaaarecord?: string;
  aaaa_part_ip_address?: string;
  aaaa_extra_create_reverse?: boolean;
  a6record?: string;
  a6_part_data?: string;
  afsdbrecord?: string;
  afsdb_part_subtype?: number;
  afsdb_part_hostname?: DNSName;
  aplrecord?: string;
  certrecord?: string;
  cert_part_type?: number;
  cert_part_key_tag?: number;
  cert_part_algorithm?: number;
  cert_part_certificate_or_crl?: string;
  cnamerecord?: string;
  cname_part_hostname?: DNSName;
  dhcidrecord?: string;
  dlvrecord?: string;
  dlv_part_key_tag?: number;
  dlv_part_algorithm?: number;
  dlv_part_digest_type?: number;
  dlv_part_digest?: string;
  dnamerecord?: string;
  dname_part_target?: DNSName;
  dsrecord?: string;
  ds_part_key_tag?: number;
  ds_part_algorithm?: number;
  ds_part_digest_type?: number;
  ds_part_digest?: string;
  hiprecord?: string;
  ipseckeyrecord?: string;
  keyrecord?: string;
  kxrecord?: string;
  kx_part_preference?: number;
  kx_part_exchanger?: DNSName;
  locrecord?: string;
  loc_part_lat_deg?: number;
  loc_part_lat_min?: number;
  loc_part_lat_sec?: Decimal;
  loc_part_lat_dir?: "N" | "S";
  loc_part_lon_deg?: number;
  loc_part_lon_min?: number;
  loc_part_lon_sec?: Decimal;
  loc_part_lon_dir?: "E" | "W";
  loc_part_altitude?: Decimal;
  loc_part_size?: Decimal;
  loc_part_h_precision?: Decimal;
  loc_part_v_precision?: Decimal;
  mxrecord?: string;
  mx_part_preference?: number;
  mx_part_exchanger?: DNSName;
  naptrrecord?: string;
  naptr_part_order?: number;
  naptr_part_preference?: number;
  naptr_part_flags?: string;
  naptr_part_service?: string;
  naptr_part_regexp?: string;
  naptr_part_replacement?: string;
  nsrecord?: string;
  ns_part_hostname?: DNSName;
  nsecrecord?: string;
  ptrrecord?: string;
  ptr_part_hostname?: DNSName;
  rrsigrecord?: string;
  rprecord?: string;
  sigrecord?: string;
  spfrecord?: string;
  srvrecord?: string;
  srv_part_priority?: number;
  srv_part_weight?: number;
  srv_part_port?: number;
  srv_part_target?: DNSName;
  sshfprecord?: string;
  sshfp_part_algorithm?: number;
  sshfp_part_fp_type?: number;
  sshfp_part_fingerprint?: string;
  tlsarecord?: string;
  tlsa_part_cert_usage?: number;
  tlsa_part_selector?: number;
  tlsa_part_matching_type?: number;
  tlsa_part_cert_association_data?: string;
  txtrecord?: string;
  txt_part_data?: string;
  urirecord?: string;
  uri_part_priority?: number;
  uri_part_weight?: number;
  uri_part_target?: string;
  setattr?: string;
  addattr?: string;
  force: boolean;
  structured: boolean;
  all: boolean;
  raw: boolean;
  version?: string;
};

export type DnsrecordDelArgs = {
  dnszoneidnsname: DNSName;
  idnsname: DNSName;
};

export type DnsrecordDelOptions = {
  dnsttl?: number;
  dnsclass?: DnsClass;
  arecord?: string;
  aaaarecord?: string;
  a6record?: string;
  afsdbrecord?: string;
  aplrecord?: string;
  certrecord?: string;
  cnamerecord?: string;
  dhcidrecord?: string;
  dlvrecord?: string;
  dnamerecord?: string;
  dsrecord?: string;
  hiprecord?: string;
  ipseckeyrecord?: string;
  keyrecord?: string;
  kxrecord?: string;
  locrecord?: string;
  mxrecord?: string;
  naptrrecord?: string;
  nsrecord?: string;
  nsecrecord?: string;
  ptrrecord?: string;
  rrsigrecord?: string;
  rprecord?: string;
  sigrecord?: string;
  spfrecord?: string;
  srvrecord?: string;
  sshfprecord?: string;
  tlsarecord?: string;
  txtrecord?: string;
  urirecord?: string;
  del_all: boolean;
  structured: boolean;
  raw: boolean;
  version?: string;
};

export type DnsrecordDelentryArgs = {
  dnszoneidnsname: DNSName;
  idnsname: DNSName;
};

export type DnsrecordDelentryOptions = {
  continue: boolean;
  version?: string;
};

export type DnsrecordFindArgs = {
  dnszoneidnsname: DNSName;
  criteria?: string;
};

export type DnsrecordFindOptions = {
  idnsname?: DNSName;
  dnsttl?: number;
  dnsclass?: DnsClass;
  arecord?: string;
  aaaarecord?: string;
  a6record?: string;
  afsdbrecord?: string;
  aplrecord?: string;
  certrecord?: string;
  cnamerecord?: string;
  dhcidrecord?: string;
  dlvrecord?: string;
  dnamerecord?: string;
  dsrecord?: string;
  hiprecord?: string;
  ipseckeyrecord?: string;
  keyrecord?: string;
  kxrecord?: string;
  locrecord?: string;
  mxrecord?: string;
  naptrrecord?: string;
  nsrecord?: string;
  nsecrecord?: string;
  ptrrecord?: string;
  rrsigrecord?: string;
  rprecord?: string;
  sigrecord?: string;
  spfrecord?: string;
  srvrecord?: string;
  sshfprecord?: string;
  tlsarecord?: string;
  txtrecord?: string;
  urirecord?: string;
  timelimit?: number;
  sizelimit?: number;
  structured: boolean;
  all: boolean;
  raw: boolean;
  version?: string;
  pkey_only?: boolean;
};

export type DnsrecordModArgs = {
  dnszoneidnsname: DNSName;
  idnsname: DNSName;
};

export type DnsrecordModOptions = {
  dnsttl?: number;
  dnsclass?: DnsClass;
  arecord?: string;
  a_part_ip_address?: string;
  aaaarecord?: string;
  aaaa_part_ip_address?: string;
  a6record?: string;
  a6_part_data?: string;
  afsdbrecord?: string;
  afsdb_part_subtype?: number;
  afsdb_part_hostname?: DNSName;
  aplrecord?: string;
  certrecord?: string;
  cert_part_type?: number;
  cert_part_key_tag?: number;
  cert_part_algorithm?: number;
  cert_part_certificate_or_crl?: string;
  cnamerecord?: string;
  cname_part_hostname?: DNSName;
  dhcidrecord?: string;
  dlvrecord?: string;
  dlv_part_key_tag?: number;
  dlv_part_algorithm?: number;
  dlv_part_digest_type?: number;
  dlv_part_digest?: string;
  dnamerecord?: string;
  dname_part_target?: DNSName;
  dsrecord?: string;
  ds_part_key_tag?: number;
  ds_part_algorithm?: number;
  ds_part_digest_type?: number;
  ds_part_digest?: string;
  hiprecord?: string;
  ipseckeyrecord?: string;
  keyrecord?: string;
  kxrecord?: string;
  kx_part_preference?: number;
  kx_part_exchanger?: DNSName;
  locrecord?: string;
  loc_part_lat_deg?: number;
  loc_part_lat_min?: number;
  loc_part_lat_sec?: Decimal;
  loc_part_lat_dir?: "N" | "S";
  loc_part_lon_deg?: number;
  loc_part_lon_min?: number;
  loc_part_lon_sec?: Decimal;
  loc_part_lon_dir?: "E" | "W";
  loc_part_altitude?: Decimal;
  loc_part_size?: Decimal;
  loc_part_h_precision?: Decimal;
  loc_part_v_precision?: Decimal;
  mxrecord?: string;
  mx_part_preference?: number;
  mx_part_exchanger?: DNSName;
  naptrrecord?: string;
  naptr_part_order?: number;
  naptr_part_preference?: number;
  naptr_part_flags?: string;
  naptr_part_service?: string;
  naptr_part_regexp?: string;
  naptr_part_replacement?: string;
  nsrecord?: string;
  ns_part_hostname?: DNSName;
  nsecrecord?: string;
  ptrrecord?: string;
  ptr_part_hostname?: DNSName;
  rrsigrecord?: string;
  rprecord?: string;
  sigrecord?: string;
  spfrecord?: string;
  srvrecord?: string;
  srv_part_priority?: number;
  srv_part_weight?: number;
  srv_part_port?: number;
  srv_part_target?: DNSName;
  sshfprecord?: string;
  sshfp_part_algorithm?: number;
  sshfp_part_fp_type?: number;
  sshfp_part_fingerprint?: string;
  tlsarecord?: string;
  tlsa_part_cert_usage?: number;
  tlsa_part_selector?: number;
  tlsa_part_matching_type?: number;
  tlsa_part_cert_association_data?: string;
  txtrecord?: string;
  txt_part_data?: string;
  urirecord?: string;
  uri_part_priority?: number;
  uri_part_weight?: number;
  uri_part_target?: string;
  setattr?: string;
  addattr?: string;
  delattr?: string;
  rights: boolean;
  structured: boolean;
  all: boolean;
  raw: boolean;
  version?: string;
  rename?: DNSName;
};

export type DnsrecordShowArgs = {
  dnszoneidnsname: DNSName;
  idnsname: DNSName;
};

export type DnsrecordShowOptions = {
  rights: boolean;
  structured: boolean;
  all: boolean;
  raw: boolean;
  version?: string;
};

export type DnsrecordSplitPartsArgs = {
  name: string;
  value: string;
};

export type DnsrecordSplitPartsOptions = {
  version?: string;
};
