name: Using Cypress GH Action

on: push

jobs:
  single-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start

      - name: run tests
        uses: cypress-io/github-action@v4
        timeout-minutes: 120
        with:
          record: true
          start: npm start
